# Generated by Django 6.1.1 on 2026-09-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance')], default='Available', max_length=20),
        ),
    ]
